export default [
    {
      id:1,
      link:"https:/127.0.0.1/jobs",
      location:'Beverlly Hils, Ontario',
      logo:"https://mckesson.wd3.myworkdayjobs.com/External_Careers/assets/logo",
      title:"Sample nurse job one",
      remote:"office-based",
      timeago:"2 hours ago",
    },
    {
      id:2,
      link:"https:/127.0.0.1/jobs",
      location:'Marple Lawn, MD',
      logo:"https://healthcareokay.com/static/media/jj.792a0ed8.jpeg",
      title:"Sample RN job two",
      remote:"office-based",
      timeago:"3 hours ago",
    },
    {
      id:3,
      link:"https:/127.0.0.1/jobs",
      location:'Belivive, MD',
      logo:"https://media.glassdoor.com/sql/15828/molina-healthcare-squarelogo-1483641096661.png",
      title:"Sample RN job 3",
      remote:"office-based",
      timeago:"3 hours ago",
    },
    {
      id:4,
      link:"https:/127.0.0.1/jobs",
      location:'Dallas, TX',
      logo:"https://healthcareokay.com/static/media/cad.e964d676.png",
      title:"Sample RN job 3",
      remote:"office-based",
      timeago:"3 hours ago",
    },
    {
      id:5,
      link:"https:/127.0.0.1/jobs",
      location:'Dallas, TX',
      logo:"https://media.glassdoor.com/sql/15828/molina-healthcare-squarelogo-1483641096661.png",
      title:"Sample job four",
      remote:"office-based",
      timeago:"3 hours ago",
    },
    {
      id:6,
      link:"https:/127.0.0.1/jobs",
      location:'Sao Palto, AR',
      logo:"https://healthcareokay.com/static/media/wal.4753fd10.png",
      title:"Sample job five",
      remote:"office-based",
      timeago:"4 hours ago",
    },
    {
        id:7,
        link:"https:/127.0.0.1/jobs",
        location:'Beverlly Hils, Ontario',
        logo:"https://mckesson.wd3.myworkdayjobs.com/External_Careers/assets/logo",
        title:"Sample nurse job one",
        remote:"office-based",
        timeago:"2 hours ago",
      },
      {
        id:8,
        link:"https:/127.0.0.1/jobs",
        location:'Marple Lawn, MD',
        logo:"https://healthcareokay.com/static/media/jj.792a0ed8.jpeg",
        title:"Sample RN job two",
        remote:"office-based",
        timeago:"3 hours ago",
      },
      {
        id:9,
        link:"https:/127.0.0.1/jobs",
        location:'Belivive, MD',
        logo:"https://media.glassdoor.com/sql/15828/molina-healthcare-squarelogo-1483641096661.png",
        title:"Sample RN job 3",
        remote:"office-based",
        timeago:"3 hours ago",
      },
      {
        id:10,
        link:"https:/127.0.0.1/jobs",
        location:'Dallas, TX',
        logo:"https://healthcareokay.com/static/media/cad.e964d676.png",
        title:"Sample RN job 3",
        remote:"office-based",
        timeago:"3 hours ago",
      },
      {
        id:11,
        link:"https:/127.0.0.1/jobs",
        location:'Dallas, TX',
        logo:"https://media.glassdoor.com/sql/15828/molina-healthcare-squarelogo-1483641096661.png",
        title:"Sample job four",
        remote:"office-based",
        timeago:"3 hours ago",
      },
      {
        id:12,
        link:"https:/127.0.0.1/jobs",
        location:'Sao Palto, AR',
        logo:"https://healthcareokay.com/static/media/wal.4753fd10.png",
        title:"Sample job five",
        remote:"office-based",
        timeago:"4 hours ago",
      },
      {
        id:13,
        link:"https:/127.0.0.1/jobs",
        location:'Beverlly Hils, Ontario',
        logo:"https://mckesson.wd3.myworkdayjobs.com/External_Careers/assets/logo",
        title:"Sample nurse job one",
        remote:"office-based",
        timeago:"2 hours ago",
      },
      {
        id:14,
        link:"https:/127.0.0.1/jobs",
        location:'Marple Lawn, MD',
        logo:"https://healthcareokay.com/static/media/jj.792a0ed8.jpeg",
        title:"Sample RN job two",
        remote:"office-based",
        timeago:"3 hours ago",
      },
      {
        id:15,
        link:"https:/127.0.0.1/jobs",
        location:'Belivive, MD',
        logo:"https://media.glassdoor.com/sql/15828/molina-healthcare-squarelogo-1483641096661.png",
        title:"Sample RN job 3",
        remote:"office-based",
        timeago:"3 hours ago",
      },
      {
        id:16,
        link:"https:/127.0.0.1/jobs",
        location:'Dallas, TX',
        logo:"https://healthcareokay.com/static/media/cad.e964d676.png",
        title:"Sample RN job 3",
        remote:"office-based",
        timeago:"3 hours ago",
      },
      {
        id:17,
        link:"https:/127.0.0.1/jobs",
        location:'Dallas, TX',
        logo:"https://media.glassdoor.com/sql/15828/molina-healthcare-squarelogo-1483641096661.png",
        title:"Sample job four",
        remote:"office-based",
        timeago:"3 hours ago",
      },
      {
        id:18,
        link:"https:/127.0.0.1/jobs",
        location:'Sao Palto, AR',
        logo:"https://healthcareokay.com/static/media/wal.4753fd10.png",
        title:"Sample job five",
        remote:"office-based",
        timeago:"4 hours ago",
      },
  ];